- package-lock.json
- package.json
- rollup.config.js
- src/assets/loading.tsx
- src/table/pagination.style.ts
- src/table/pagination.tsx
- src/table/table.tsx
- stories/table.stories.tsx
- sửa giao diện loading
- sửa gioa diện pagination
- sửa config import file png
> Sửa giao diện Loading và Pagination

- package.json
- src/table/table.tsx
Thêm defendencie location để lắng nghe param filter
> Thêm defendencie location để lắng nghe param filter

- package-lock.json
- src/table/table.tsx
- src/table/types.ts
- stories/table.stories.tsx
> Them render trong TableProps

- package.json
- src/table/types.ts
Update version build dev
them type filter
> Update version build dev

- .github/workflows/npm-publish-beta.yml
- package.json
> Remove run sonar - 1.0.20

- package-lock.json
- src/table/table.tsx
Fix error, chuyen sai type table
> Fix error, chuyen sai type table

- package.json
- src/hooks/use-filter.tsx
- src/table/table.test.tsx
- src/table/table.tsx
- src/table/types.ts
- stories/refresh.stories.tsx
- stories/table.stories.tsx
> Them generic table - 1.0.21

- package.json
> Update version beta 1.1.1

- package.json
- src/table/types.ts
fix render table không bắt buộc
Up version build beta - 1.2.01
> Up version build beta - 1.2.01

- package.json
- src/table/table.tsx
Fix add key list table - 1.2.02
> Fix add key list table - 1.2.02

- package.json
- src/table/error.tsx
- src/table/table.tsx
fix table  > khi load data loi > show loi > het loi khong show data
hien thi loi
> fix table  > khi load data loi > show loi > het loi khong show data

- .storybook/preview-head.html
- package.json
- src/styles/pagination.style.ts
- src/table/pagination.tsx
- Bỏ font awesome icon => thay bằng svg jsx
- Sửa hiển thị khi data phân trang khi data truyền vào bị lỗi
> Sửa phần Pagination: bỏ font awesome icon + sửa hiển thị khi data phân trang bị lỗi

- package.json
- src/hooks/use-filter.tsx
- Fix array type for useTableFilter
- Update version
> Fix array type and update version

- src/hooks/use-filter.tsx
- stories/filter.stories.tsx
Update filter 
- Allow to get filter of 1 fields 
- Delete filter key
- Get filter of all prefix
> update with filter 1 key or all keys

- src/table/table-loading.tsx
- stories/table-default.stories.tsx
Sửa phần UI khi loading bị trắng
> Sửa phần UI khi loading bị trắng

- src/hooks/use-filter.tsx
- src/table/pagination.tsx
- src/table/table-body.tsx
- src/table/table.tsx
- Sửa lại các class name về overflow (thẻ td và div root table)
- Sửa lại hook useTableFilter (khi filter param khác 'page' thì query page = 1)
- Ẩn phân trang khi total page < 2
> Sửa lại hook useTableFilter và logic phần phân trang

- src/hooks/use-filter.tsx
- src/table/error.tsx
- src/table/pagination.tsx
- src/table/table.tsx
- stories/table-default.stories.tsx
Sửa lại UI loading và Hiển thị message lỗi
> Sửa lại UI loading và Hiển thị message lỗi

- package.json
- src/hooks/use-filter.tsx
Sửa lại hook useTableFilter (param page bị thiếu prefix)
> Sửa lại hook useTableFilter

- src/hooks/use-filter.tsx
- src/hooks/use-sort.tsx
- src/table/table-body.tsx
- src/table/table.tsx
- src/utils/helper.ts
- Sửa UI row table: khi hover thay đổi background
- Các param filter, sort khi không có value (empty string, null, undefined) => không đẩy lên url
- Ẩn hẳn phần pagination khi không cần thiết (hiện tại đang hiện ô trắng)
> Sửa UI pagination, table row

- src/table/table.tsx
Sửa lại UI pagination ẩn khoảng trắng khi không có data
> Sửa UI pagination

- .storybook/main.js
- package.json
- src/hooks/use-filter.tsx
- src/table/table.tsx
Sửa lại class name div wraper table
(Sửa lỗi: nếu table cần scroll x, khi không có data đang không scroll x)
> Sửa lại class name div wraper table

- src/hooks/use-filter.tsx
- src/styles/filter.style.ts
- src/table/filter.tsx
- stories/table-filters.stories.tsx
> Set filter: allow to send params with array
